### ISSUE TITLE
Add google/facebook login to this example

### ISSUE THREAD

**Issue by bassment** [stormpath/stormpath-express-react-example#1]
Hi, @typerandom !

First of all, thanks for sharing such a great react login/register service which works just perfect! ;)
But, i'm very interested in seeing here an example for login with social network accounts, like facebook or google. 

Actually I tried to implement this trough JSON API that you provide in a docs. I send json object(provider data with a access_token) as a POST to server and login successfully! 

But the problem I faced is - since my app is React SPA, I got 401 Unauthorized error on first Login page load => Then I login with facebook or google and it get back to Login page => In my ajax POST request callback I tried to redirect to protected route, right after facebook authorization data is checked by server. But in my console i still have this 401 error, so my callback tried to redirect, but since it see 401 error, my redirect for the authenticated route is not working ;(

It looks that express-stormpath service doesn't return status 200 to substitute status 401 when it checks access-tokens from facebook or google. That's why i posted it to issues.

Maybe i'm wrong on my guess and the problem is somewhere in my code. I would be very thankful if you'll check my working repository ;)
Here is the link to login page - https://github.com/codterpin/automate/tree/login/client/components/Login
JSON helper - https://github.com/codterpin/automate/blob/login/client/helpers/JsRestHelper.js

Much thanks in advance!

**Comment by rorheden** [comment]
Thank you!

From what I can see so far this looks awesome! :beers: Unfortunately I don't have time to dig into this right now and why it's not exactly working, but I'll allocate some time soon so that I can get back to you.

Meanwhile I have created a new issue in the SDK, since this is something that we'd really want to get in there, also it helps us track this specific feature/issue:)

https://github.com/stormpath/stormpath-sdk-react/issues/14

Cheers!

**Comment by bassment** [comment]
Thanks!

I just want to inform you that I figure out the bug myself ;) I changed the workflow and connect my request via flux (previously it was connected directly from my component).
Still facebook's flux architecture looks very verbose and tedious for me. So i'm looking forward for this enhancement - https://github.com/stormpath/stormpath-sdk-react/issues/3 ;)
I also can recommend this - http://alt.js.org/  as an alternative to redux. Alt looks very concise and declarative, using es7 decorators. Anyway I would be happy to see any implementation of two  - redux OR alt  Or both ;)

Keep the work up! You guys helping a lot of people!  Thanks a lot!

**Comment by rorheden** [comment]
@codterpin Awesome that you were able to work it out yourself!

And I agree with flux being tedious. I'm cheering more for Redux. Haven't seen Alt before, but that looks really sweet. Created a issue for it in the SDK so that it isn't lost: https://github.com/stormpath/stormpath-sdk-react/issues/16

So thanks for mentioning that.

Let me know if there is anything else in the SDK that you feel isn't working/you'd like to work better :)

Cheers!
