### ISSUE TITLE
Odd Registration Behavior

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-express-react-example#14]
I'm going through the react / express stormpath console quickstart right now.

After opening this app, and clicking register, and typing in my info, I get odd behavior. Here's what I see after I create my account:

![screenshot 2016-08-05 10 48 04](https://cloud.githubusercontent.com/assets/90247/17445523/38ea9ea6-5afa-11e6-8e90-37e391b8cd24.png)

I'm kept on the same page, which makes it LOOK like my registration didn't work. This is really confusing. After registration, I should be redirected to the dashboard.

**Comment by rorheden** [comment]
I'm a little bit confused. How do you mean that you are kept on the same page? That it visually looks like the same page? For me the two pages look different. Sure, there are two forms. But the content is different:) Also page header says "My Profile" instead of "Login".

This should be the same example app that we have for Angular.js, so I think the behaviour is pretty much the same there. What do you mean by the dashboard? We don't have any "dashboard" in these example apps...

Do you mean the `/`(default home) route?

**Comment by rdegges** [comment]
Whoops. I just now realized after looking at your comment that this is indeed a separate page. I think we should visually change this so it looks different than the registration page. I was really confused using this at first because I assumed my registration didn't work.

Feels sorta odd.

Might be nice to have some style in here =)

**Comment by robertjd** [comment]
I also think that this behavior is confusing.  After login you should go to the homepage of the application, with the option to click into your profile from the top menu.
